version: "3.7"
services:
    nginx:
        container_name: ${COMPOSE_PROJECT_NAME}-nginx
        restart: always
        build:
            context: ./docker/containers/nginx
            args:
                - BASIC_USERNAME=${AUTH_BASIC_ADMIN_LOGIN}
                - BASIC_PASSWORD=${AUTH_BASIC_ADMIN_PASSWORD}
        volumes:
            - .:/source
            - ./docker/logs/nginx:/var/log/nginx/
        ports:
            - "${EXTERNAL_NGINX_HTTP_PORT}:80"
        environment:
            - TZ=Europe/Moscow
        depends_on:
            - php-fpm
        logging:
            driver: "json-file"
            options:
                max-size: "5m"
                max-file: "5"
                mode: "non-blocking"
                tag: "logging-webserver"
        networks:
            - api

    php-fpm:
        container_name: ${COMPOSE_PROJECT_NAME}-php-fpm
        restart: always
        build:
            context: ./docker/containers/php-fpm
            args:
                UID: ${USER_ID}
                GID: ${GROUP_ID}
        volumes:
            - .:/source
            - ./docker/logs/php-fpm:/var/log/php-fpm/
        environment:
            - TZ=Europe/Moscow
        networks:
            - api

    php-supervisor:
        container_name: ${COMPOSE_PROJECT_NAME}-supervisor
        restart: always
        build:
            context: ./docker/containers/php-supervisor
            args:
                UID: ${USER_ID}
                GID: ${GROUP_ID}
        environment:
            - TZ=Europe/Moscow
        volumes:
            - .:/source
            - ./docker/logs/php-supervisor/supervisor:/var/log/supervisor/
        networks:
            - api

    php-cron:
        container_name: ${COMPOSE_PROJECT_NAME}-cron
        restart: always
        build:
            context: ./docker/containers/php-cron
            args:
                UID: ${USER_ID}
                GID: ${GROUP_ID}
        environment:
            - TZ=Europe/Moscow
        volumes:
            - .:/source
            - ./docker/logs/php-cron/cron:/var/log/cron/
        networks:
            - api

    db:
        container_name: ${COMPOSE_PROJECT_NAME}-db
        image: postgres:17
        restart: always
        volumes:
            - ./docker/postgres/data:/var/lib/postgres/data
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "5432:5432"
        networks:
            - api

    redis:
        image: redis:6.2-alpine
        container_name: ${COMPOSE_PROJECT_NAME}-redis
        restart: always
        environment:
            - TZ=Europe/Moscow
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        ports:
            - '${EXTERNAL_REDIS_PORT}:6379'
        volumes:
            - ./docker/containers/redis/data:/data
            - ./docker/containers/redis/redis.conf:/usr/local/etc/redis/redis.conf
            - ./docker/logs/redis:/var/log
        command: redis-server --include /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
        logging:
            driver: "json-file"
            options:
                max-size: "5m"
                max-file: "5"
                mode: "non-blocking"
                tag: "logging-redis"
        networks:
            - api
networks:
    api:
        name: ${COMPOSE_NETWORK_NAME}
        driver: bridge
